---
title: "fmt2-NMD"
output: github_document
---


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "../figures/README-",
  out.width = "100%"
)
library(ggvegan)
library(vegan)
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(readr)


```

## get data

```{r }

nmddf<-read.csv("../data/fmt2-nmd.csv",header = T)



```

## Analysis


```{r pressure, echo=FALSE}

com=nmddf[, 5:ncol(nmddf)]

env=nmddf[, 1:4]


```




```{r}

m_com = as.matrix(com)
nmds <- metaMDS(com, distance = "bray", k = 3)


ano = anosim(m_com, nmddf$Group, distance = "bray", permutations = 999)


summary(ano)

plot(ano, ylab=" ",xlab=" ")


ano1 = anosim(m_com, nmddf$DPM, distance = "bray", permutations = 999)

summary(ano1)

plot(ano1, ylab=" ",xlab=" ")


```


### adonis, check the variation in the data.

p-value is small, there is significant variation by treatment group.

```{r}

fit1<-adonis2(com~`Group`, data=env, permutations = 999, method = "bray")
distance_data<-vegdist(com)
anova(betadisper(distance_data,env$Group))

```


